# Generated by Django 5.2.8 on 2025-12-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Giảng viên', 'verbose_name_plural': 'Danh sách Giảng viên'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Môn học (Module)', 'verbose_name_plural': 'Danh sách Môn học'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Đơn đăng ký', 'verbose_name_plural': 'Danh sách Đăng ký'},
        ),
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'verbose_name': 'Lịch học', 'verbose_name_plural': 'Quản lý Lịch học'},
        ),
        migrations.AddField(
            model_name='module',
            name='icon_name',
            field=models.CharField(default='book', max_length=50, verbose_name='Tên Icon (VD: users, trending)'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Link Ảnh'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Họ và Tên'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Học hàm/Học vị'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='module',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Link Ảnh'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên Môn học'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Họ tên học viên'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nguồn/Chức vụ'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='date_str',
            field=models.CharField(max_length=50, verbose_name='Ngày hiển thị (VD: 06/12)'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='item_type',
            field=models.CharField(choices=[('class', 'Buổi học'), ('break', 'Nghỉ Đông'), ('holiday', 'Nghỉ Lễ')], default='class', max_length=20, verbose_name='Loại lịch'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.instructor', verbose_name='Giảng viên'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Chủ đề'),
        ),
    ]
