# Generated by Django 5.2.8 on 2025-12-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_instructor_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='duration',
            field=models.CharField(default='09:00 - 16:30', max_length=100, verbose_name='Thời lượng (Giờ học)'),
        ),
    ]
