# Generated by Django 5.2.8 on 2025-12-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_scheduleitem_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả thêm'),
        ),
    ]
