# Generated by Django 5.2.8 on 2025-12-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_instructor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='overviews/covers/', verbose_name='Ảnh bìa (Lớn)')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề trụ cột')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('icon_type', models.CharField(choices=[('strategy', 'Chiến lược (Mũi tên lên)'), ('finance', 'Tài chính (Sách/Ví)'), ('leadership', 'Lãnh đạo (Nhóm người)'), ('marketing', 'Marketing (Huy chương/Loa)')], default='strategy', max_length=50, verbose_name='Loại Icon hiển thị')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Trụ cột khóa học',
                'verbose_name_plural': 'Tổng quan (4 Trụ cột)',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='Upload Ảnh'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Hoặc Link Ảnh Online'),
        ),
    ]
