# Generated by Django 5.2.8 on 2025-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseoverview_instructor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='overviews/icons/', verbose_name='Icon (Ảnh nhỏ)'),
        ),
    ]
