# Generated by Django 5.2.8 on 2025-12-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseoverview_icon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoverview',
            name='icon_image',
        ),
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='modules/', verbose_name='Upload Ảnh bìa'),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('new', 'Mới đăng ký'), ('contacted', 'Đã liên hệ'), ('paid', 'Đã thanh toán'), ('canceled', 'Hủy bỏ')], default='new', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='module',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Hoặc Link Ảnh Online'),
        ),
    ]
