# Generated by Django 5.2.8 on 2025-12-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_courseoverview_icon_image_module_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Quản Trị', max_length=200, verbose_name='Tiêu đề Hero (Dòng 1)')),
                ('hero_subtitle', models.CharField(default='Chuyển Đổi Số Y Tế', max_length=200, verbose_name='Tiêu đề Hero (Dòng 2 - Màu vàng)')),
                ('stat_1', models.CharField(default='10', max_length=50, verbose_name='Số liệu 1 (Số buổi)')),
                ('stat_2', models.CharField(default='Hybrid', max_length=50, verbose_name='Số liệu 2 (Hình thức)')),
                ('stat_3', models.CharField(default='100%', max_length=50, verbose_name='Số liệu 3 (Case Study)')),
                ('stat_4', models.CharField(default='TRAF', max_length=50, verbose_name='Số liệu 4 (Giảng viên)')),
                ('benefit_title', models.CharField(default='Giải quyết bài toán thực tế...', max_length=200, verbose_name='Tiêu đề Lợi ích')),
                ('benefit_desc', models.TextField(default='Chương trình Mini MBA Y tế được thiết kế...', verbose_name='Mô tả Lợi ích')),
                ('benefits_list', models.TextField(default='Học theo mô hình Hybrid\nLý thuyết cô đọng\nCase Study thực tế', help_text='Xuống dòng để tách các ý', verbose_name='Danh sách lợi ích (Mỗi dòng 1 ý)')),
            ],
            options={
                'verbose_name': 'Cấu hình Trang chủ',
                'verbose_name_plural': 'Cấu hình Trang chủ',
            },
        ),
    ]
