# Generated by Django 5.2.8 on 2025-12-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_homepageconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageconfig',
            options={'verbose_name': 'Cấu hình Trang chủ'},
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả (EN)'),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề (EN)'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='benefit_desc_en',
            field=models.TextField(blank=True, default='...', verbose_name='Mô tả Lợi ích (EN)'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='benefit_title_en',
            field=models.CharField(blank=True, default='Solving...', max_length=200, verbose_name='Tiêu đề Lợi ích (EN)'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='benefits_list_en',
            field=models.TextField(blank=True, default='...', help_text='Xuống dòng để tách ý', verbose_name='List Lợi ích (EN)'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, default='Healthcare Digital Transformation', max_length=200, verbose_name='Tiêu đề 2 (EN)'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='hero_title_en',
            field=models.CharField(blank=True, default='Management', max_length=200, verbose_name='Tiêu đề 1 (EN)'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả thêm (EN)'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chức vụ (EN)'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Học hàm/Học vị (EN)'),
        ),
        migrations.AddField(
            model_name='module',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả (EN)'),
        ),
        migrations.AddField(
            model_name='module',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên Môn học (EN)'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='topic_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chủ đề (EN)'),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='overviews/covers/', verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='description',
            field=models.TextField(verbose_name='Mô tả (VN)'),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='icon_type',
            field=models.CharField(choices=[('strategy', 'Chiến lược'), ('finance', 'Tài chính'), ('leadership', 'Lãnh đạo'), ('marketing', 'Marketing')], default='strategy', max_length=50, verbose_name='Loại Icon'),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề (VN)'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='benefit_desc',
            field=models.TextField(default='...', verbose_name='Mô tả Lợi ích (VN)'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='benefit_title',
            field=models.CharField(default='Giải quyết...', max_length=200, verbose_name='Tiêu đề Lợi ích (VN)'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='benefits_list',
            field=models.TextField(default='...', help_text='Xuống dòng để tách ý', verbose_name='List Lợi ích (VN)'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='hero_subtitle',
            field=models.CharField(default='Chuyển Đổi Số Y Tế', max_length=200, verbose_name='Tiêu đề 2 (VN)'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='hero_title',
            field=models.CharField(default='Quản Trị', max_length=200, verbose_name='Tiêu đề 1 (VN)'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='stat_1',
            field=models.CharField(default='10', max_length=50, verbose_name='Số liệu 1'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='stat_2',
            field=models.CharField(default='Hybrid', max_length=50, verbose_name='Số liệu 2'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='stat_3',
            field=models.CharField(default='100%', max_length=50, verbose_name='Số liệu 3'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='stat_4',
            field=models.CharField(default='TRAF', max_length=50, verbose_name='Số liệu 4'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả thêm (VN)'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Chức vụ (VN)'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Học hàm/Học vị (VN)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(verbose_name='Mô tả (VN)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='icon_name',
            field=models.CharField(default='book', max_length=50, verbose_name='Tên Icon'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên Môn học (VN)'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='date_str',
            field=models.CharField(max_length=50, verbose_name='Ngày hiển thị'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='duration',
            field=models.CharField(default='09:00 - 16:30', max_length=100, verbose_name='Thời lượng'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Chủ đề (VN)'),
        ),
    ]
