# Generated by Django 5.2.8 on 2025-12-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_homepageconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='footer_text',
            field=models.CharField(default='© 2025 TBI. All rights reserved.', max_length=200, verbose_name='Footer Text (VN)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='footer_text_en',
            field=models.CharField(blank=True, default='© 2025 TBI. All rights reserved.', max_length=200, verbose_name='Footer Text (EN)'),
        ),
    ]
