# Generated by Django 5.2.8 on 2025-12-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_registration_footer_text_registration_footer_text_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageconfig',
            name='benefit_title',
            field=models.TextField(default='Giải quyết bài toán thực tế của bản thân\n& tổ chức', verbose_name='Tiêu đề Lợi ích (VN)'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='benefit_title_en',
            field=models.TextField(blank=True, default='Solving real problems for yourself\n& your organization', verbose_name='Tiêu đề Lợi ích (EN)'),
        ),
    ]
