# Generated by Django 5.2.8 on 2025-12-26 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_registration_footer_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên bài học (VN)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên bài học (EN)')),
                ('slug', models.SlugField(help_text='Tự động tạo từ tiêu đề', max_length=250, unique=True, verbose_name='Slug (URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật cuối')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Thuộc Môn học')),
            ],
            options={
                'verbose_name': 'Bài học (Lesson)',
                'verbose_name_plural': 'Quản lý Bài học',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên tài liệu (VN)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên tài liệu (EN)')),
                ('material_type', models.CharField(choices=[('video', 'Video Bài giảng'), ('pdf', 'Slide / PDF'), ('doc', 'Tài liệu đọc')], default='pdf', max_length=20, verbose_name='Loại tài liệu')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx'])], verbose_name='Upload File')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Link Video (Youtube/Vimeo)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Học thử (Public)?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson', verbose_name='Thuộc Bài học')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Kho Tài liệu',
                'ordering': ['order'],
            },
        ),
    ]
