# Generated by Django 5.2.8 on 2025-12-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_usernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề bài viết')),
                ('slug', models.SlugField(help_text='Tự động tạo từ tiêu đề', max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('category', models.CharField(choices=[('news', 'Tin tức Y tế'), ('research', 'Nghiên cứu Khoa học'), ('perspective', 'Góc nhìn Chuyên gia')], default='perspective', max_length=20, verbose_name='Chuyên mục')),
                ('author', models.CharField(default='TBI Research Team', max_length=100, verbose_name='Tác giả')),
                ('summary', models.TextField(help_text='Hiện ở trang danh sách', verbose_name='Tóm tắt ngắn (Sapo)')),
                ('content', models.TextField(help_text='Chấp nhận mã HTML cơ bản', verbose_name='Nội dung chi tiết')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='research_covers/', verbose_name='Ảnh bìa')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='research_pdfs/', verbose_name='File PDF Full (Download)')),
                ('is_public', models.BooleanField(default=True, verbose_name='Công khai?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name': 'Bài nghiên cứu',
                'verbose_name_plural': 'Kho Research & Blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
