# Generated by Django 5.2.8 on 2025-12-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_researchpost_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpost',
            name='summary',
            field=models.TextField(help_text='Hiện ở trang danh sách (Cập nhật)', verbose_name='Tóm tắt ngắn'),
        ),
    ]
