# Generated by Django 5.2.8 on 2025-12-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_researchpost_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên học viên')),
                ('role', models.CharField(help_text='Ví dụ: Giám đốc BV Đa khoa X', max_length=200, verbose_name='Chức vụ/Nơi công tác')),
                ('content', models.TextField(verbose_name='Lời nhận xét')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Ảnh đại diện')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ý kiến học viên',
                'verbose_name_plural': 'Quản lý Ý kiến học viên',
            },
        ),
    ]
