# Generated by Django 5.2.8 on 2025-12-30 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Đơn đăng ký học', 'verbose_name_plural': 'Quản lý Đăng ký'},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='position',
        ),
        migrations.AddField(
            model_name='registration',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú thêm'),
        ),
        migrations.AddField(
            model_name='registration',
            name='selected_module',
            field=models.ForeignKey(blank=True, help_text='Để trống nếu đăng ký toàn khóa Mini MBA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.module', verbose_name='Module đăng ký'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('new', 'Mới đăng ký'), ('consulted', 'Đã tư vấn'), ('paid', 'Đã đóng tiền'), ('canceled', 'Hủy bỏ')], default='new', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
