# Generated by Django 5.2.8 on 2025-12-30 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Học phần (Module)', 'verbose_name_plural': 'Quản lý Modules'},
        ),
        migrations.RemoveField(
            model_name='module',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='module',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='module',
            name='image',
        ),
        migrations.RemoveField(
            model_name='module',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='module',
            name='title_en',
        ),
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='duration',
            field=models.CharField(default='4 giờ', help_text='Ví dụ: 4 Buổi học', max_length=50, verbose_name='Thời lượng'),
        ),
        migrations.AddField(
            model_name='module',
            name='has_certificate',
            field=models.BooleanField(default=True, verbose_name='Có cấp chứng chỉ không?'),
        ),
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang tuyển sinh'),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Số thứ tự (1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(verbose_name='Mô tả ngắn'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên Module'),
        ),
    ]
