# Generated by Django 5.2.8 on 2026-01-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_module_options_remove_module_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả ngắn (EN)'),
        ),
        migrations.AddField(
            model_name='module',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên Module (EN)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Lời nhận xét (EN)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chức vụ (EN)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(verbose_name='Mô tả ngắn (VN)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='duration',
            field=models.CharField(default='4 giờ', max_length=50, verbose_name='Thời lượng'),
        ),
        migrations.AlterField(
            model_name='module',
            name='has_certificate',
            field=models.BooleanField(default=True, verbose_name='Có cấp chứng chỉ?'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Số thứ tự'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tên Module (VN)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(verbose_name='Lời nhận xét (VN)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(max_length=200, verbose_name='Chức vụ/Nơi công tác (VN)'),
        ),
    ]
