# Generated by Django 5.2.8 on 2026-01-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_module_description_en_module_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên dịch vụ (VN)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên dịch vụ (EN)')),
                ('description', models.TextField(verbose_name='Mô tả ngắn (VN)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Mô tả ngắn (EN)')),
                ('icon_name', models.CharField(choices=[('Cpu', 'Công nghệ (Chip)'), ('Activity', 'Y tế (Nhịp tim)'), ('Layers', 'Chiến lược (Lớp)'), ('Users', 'Nhân sự'), ('Zap', 'Tốc độ'), ('ShieldCheck', 'Bảo mật')], default='Cpu', max_length=50, verbose_name='Icon')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung chi tiết (HTML)')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Dịch vụ Tư vấn',
                'verbose_name_plural': 'Quản lý Dịch vụ Tư vấn',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên đối tác')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Logo đối tác')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website (nếu có)')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Đối tác / Khách hàng',
                'verbose_name_plural': 'Quản lý Đối tác',
                'ordering': ['order'],
            },
        ),
    ]
