# Generated by Django 5.2.8 on 2026-01-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_consultingservice_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên chương trình (VN)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên chương trình (EN)')),
                ('description', models.TextField(verbose_name='Mô tả ngắn (VN)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Mô tả ngắn (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name='Ảnh/Icon')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Đường dẫn (Link)')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Chương trình Đào tạo',
                'verbose_name_plural': 'Danh mục Chương trình',
                'ordering': ['order'],
            },
        ),
    ]
