# Generated by Django 5.2.8 on 2026-01-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_trainingprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralHomepageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Kiến Tạo Tương Lai Y Tế', max_length=200, verbose_name='Tiêu đề Banner (VN)')),
                ('hero_title_en', models.CharField(blank=True, default='Shaping Future Healthcare', max_length=200, verbose_name='Tiêu đề Banner (EN)')),
                ('hero_slogan', models.CharField(default='Giải pháp Y tế Thông minh Toàn diện', max_length=200, verbose_name='Slogan (VN)')),
                ('hero_slogan_en', models.CharField(blank=True, default='Comprehensive Smart Health Solutions', max_length=200, verbose_name='Slogan (EN)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Ảnh nền Banner')),
                ('footer_text', models.CharField(default='© 2025 Smart Health Solutions.', max_length=300, verbose_name='Footer Text (VN)')),
                ('footer_text_en', models.CharField(blank=True, default='© 2025 Smart Health Solutions.', max_length=300, verbose_name='Footer Text (EN)')),
            ],
            options={
                'verbose_name': 'Cấu hình Trang chủ Tổng',
            },
        ),
        migrations.RenameModel(
            old_name='HomepageConfig',
            new_name='MiniMBAConfig',
        ),
    ]
