# Generated by Django 5.2.8 on 2026-01-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_generalhomepageconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalhomepageconfig',
            name='founder_bio',
            field=models.TextField(default='...', verbose_name='Tiểu sử Founder (VN)'),
        ),
        migrations.AddField(
            model_name='generalhomepageconfig',
            name='founder_bio_en',
            field=models.TextField(blank=True, default='...', verbose_name='Tiểu sử Founder (EN)'),
        ),
        migrations.AddField(
            model_name='generalhomepageconfig',
            name='founder_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/founder/', verbose_name='Ảnh chân dung Founder'),
        ),
        migrations.AddField(
            model_name='generalhomepageconfig',
            name='founder_name',
            field=models.CharField(default='Mr. Trương Minh Chương', max_length=100, verbose_name='Tên Founder'),
        ),
        migrations.AddField(
            model_name='generalhomepageconfig',
            name='founder_role',
            field=models.CharField(default='Founder & CEO', max_length=100, verbose_name='Chức danh (VN)'),
        ),
        migrations.AddField(
            model_name='generalhomepageconfig',
            name='founder_role_en',
            field=models.CharField(blank=True, default='Founder & CEO', max_length=100, verbose_name='Chức danh (EN)'),
        ),
    ]
