# Generated by Django 5.2.8 on 2026-01-06 15:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_generalhomepageconfig_founder_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_vi', models.CharField(max_length=255, verbose_name='Tên Giải pháp (VI)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Solution Name (EN)')),
                ('thumbnail', models.ImageField(upload_to='solutions_thumbs/', verbose_name='Ảnh đại diện')),
                ('context_vi', ckeditor.fields.RichTextField(verbose_name='[Tab 1] Bối cảnh/Vấn đề (VI)')),
                ('context_en', ckeditor.fields.RichTextField(verbose_name='[Tab 1] Context/Problem (EN)')),
                ('solution_vi', ckeditor.fields.RichTextField(verbose_name='[Tab 2] Giải pháp SHS (VI)')),
                ('solution_en', ckeditor.fields.RichTextField(verbose_name='[Tab 2] SHS Solution (EN)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Bài viết Thư viện Giải pháp',
                'verbose_name_plural': 'Thư viện Giải pháp',
                'ordering': ['-created_at'],
            },
        ),
    ]
