# Generated by Django 5.2.8 on 2026-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_consultingsolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingsolution',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='solutions_thumbs/', verbose_name='Ảnh đại diện'),
        ),
    ]
