# Generated by Django 5.2.8 on 2026-01-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_consultingsolution_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='icon_type',
            field=models.CharField(choices=[('strategy', 'Chiến lược'), ('finance', 'Tài chính'), ('leadership', 'Lãnh đạo'), ('marketing', 'Marketing'), ('map', 'Map'), ('database', 'Database'), ('rocket', 'Rocket'), ('cpu', 'CPU'), ('setting', 'Settings')], default='strategy', max_length=50, verbose_name='Loại Icon'),
        ),
    ]
