# Generated by Django 5.2.8 on 2026-01-14 14:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_courseoverview_icon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpost',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nội dung (Tiếng Anh)'),
        ),
        migrations.AddField(
            model_name='researchpost',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tóm tắt (Tiếng Anh)'),
        ),
        migrations.AddField(
            model_name='researchpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề (Tiếng Anh)'),
        ),
        migrations.AlterField(
            model_name='researchpost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='researchpost',
            name='summary',
            field=models.TextField(),
        ),
    ]
