# Generated by Django 5.2.8 on 2026-01-15 08:19

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_healthcareinstructor_healthcarembaconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JCIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='JCI Concepts – Quản Lý Chất Lượng', max_length=200, verbose_name='Tiêu đề Banner (VN)')),
                ('hero_title_en', models.CharField(blank=True, default='JCI Concepts – Quality Management', max_length=200, verbose_name='Tiêu đề Banner (EN)')),
                ('hero_slogan', models.CharField(default='Nâng Tầm Chất Lượng Bệnh Viện Theo Chuẩn JCI', max_length=300, verbose_name='Slogan (VN)')),
                ('hero_slogan_en', models.CharField(blank=True, default='Elevating Hospital Quality to JCI Standards', max_length=300, verbose_name='Slogan (EN)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='jci/', verbose_name='Ảnh nền Banner')),
                ('brochure_file', models.FileField(blank=True, null=True, upload_to='jci/brochures/', verbose_name='File Brochure')),
                ('intro_title', models.CharField(default='Về khóa học JCI', max_length=200, verbose_name='Tiêu đề Giới thiệu (VN)')),
                ('intro_title_en', models.CharField(blank=True, default='About JCI Course', max_length=200, verbose_name='Tiêu đề Giới thiệu (EN)')),
                ('intro_desc', ckeditor.fields.RichTextField(verbose_name='Mô tả giới thiệu (VN)')),
                ('intro_desc_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mô tả giới thiệu (EN)')),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='jci/', verbose_name='Ảnh Giới thiệu')),
            ],
            options={
                'verbose_name': 'Cấu hình Trang JCI',
                'verbose_name_plural': 'Cấu hình Trang JCI',
            },
        ),
        migrations.CreateModel(
            name='JCIInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên giảng viên')),
                ('title', models.CharField(max_length=100, verbose_name='Chức danh (VN)')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='Chức danh (EN)')),
                ('bio', models.TextField(blank=True, verbose_name='Tiểu sử (VN)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Tiểu sử (EN)')),
                ('avatar', models.ImageField(upload_to='jci_instructors/', verbose_name='Ảnh đại diện')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': '[JCI] Giảng viên',
                'verbose_name_plural': '[JCI] Danh sách Giảng viên',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JCIModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên chuyên đề (VN)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Tên chuyên đề (EN)')),
                ('description', models.TextField(verbose_name='Mô tả (VN)')),
                ('description_en', models.TextField(blank=True, verbose_name='Mô tả (EN)')),
                ('icon_name', models.CharField(default='ShieldCheck', max_length=50, verbose_name='Tên Icon (Lucide)')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': '[JCI] Chuyên đề',
                'verbose_name_plural': '[JCI] Danh sách Chuyên đề',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JCIRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Bệnh viện/Đơn vị')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Chức vụ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Đã liên hệ?')),
            ],
            options={
                'verbose_name': '[JCI] Đăng ký tư vấn',
                'verbose_name_plural': '[JCI] Danh sách Đăng ký',
            },
        ),
        migrations.CreateModel(
            name='JCISchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Chủ đề buổi học (VN)')),
                ('topic_en', models.CharField(blank=True, max_length=200, verbose_name='Chủ đề buổi học (EN)')),
                ('date', models.DateField(verbose_name='Ngày học')),
                ('time_start', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('time_end', models.TimeField(verbose_name='Giờ kết thúc')),
                ('is_online', models.BooleanField(default=True, verbose_name='Học Online?')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.jciinstructor', verbose_name='Giảng viên phụ trách')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.jcimodule', verbose_name='Thuộc Chuyên đề')),
            ],
            options={
                'verbose_name': '[JCI] Lịch học',
                'verbose_name_plural': '[JCI] Lịch khai giảng',
                'ordering': ['date', 'time_start'],
            },
        ),
    ]
