# Generated by Django 5.2.8 on 2026-01-17 07:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_jciconfig_jciinstructor_jcimodule_jciregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiHealthcareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_vi', models.CharField(default='AI in Healthcare', max_length=255)),
                ('hero_title_en', models.CharField(default='AI in Healthcare', max_length=255)),
                ('hero_subtitle_vi', models.CharField(default='Ứng dụng Trí tuệ Nhân tạo trong Y tế', max_length=255)),
                ('hero_subtitle_en', models.CharField(default='Artificial Intelligence in Medicine', max_length=255)),
                ('hero_desc_vi', models.TextField(default='Chương trình đào tạo chuyên sâu...')),
                ('hero_desc_en', models.TextField(default='Intensive training program...')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='ai_healthcare/hero/')),
                ('brochure_file', models.FileField(blank=True, null=True, upload_to='ai_healthcare/brochures/')),
                ('stat_duration', models.CharField(default='43 Giờ', max_length=50)),
                ('stat_format', models.CharField(default='Hybrid', max_length=50)),
                ('stat_cert', models.CharField(default='TAMI Certificate', max_length=50)),
            ],
            options={
                'verbose_name': 'Cấu hình Trang AI Healthcare',
                'verbose_name_plural': '1. Cấu hình Trang AI Healthcare',
            },
        ),
        migrations.CreateModel(
            name='AiHealthcareInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title_vi', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('bio_vi', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='ai_healthcare/instructors/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Giảng viên AI',
                'verbose_name_plural': '3. Giảng viên AI',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AiHealthcareModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_vi', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('week_label', models.CharField(help_text='Ví dụ: Week 1, Tuần 1', max_length=50)),
                ('description_vi', ckeditor.fields.RichTextField()),
                ('description_en', ckeditor.fields.RichTextField()),
                ('icon_name', models.CharField(default='BookOpen', help_text='Tên icon từ thư viện Lucide (vd: Database, BrainCircuit, Code...)', max_length=50)),
                ('format', models.CharField(default='Online', help_text='Online / Offline / Hybrid', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Chuyên đề AI (Module)',
                'verbose_name_plural': '2. Chuyên đề AI (Modules)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AiHealthcareRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đăng ký AI Healthcare',
                'verbose_name_plural': '5. Danh sách Đăng ký AI',
            },
        ),
        migrations.CreateModel(
            name='AiHealthcareSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('topic_vi', models.CharField(max_length=255)),
                ('topic_en', models.CharField(max_length=255)),
                ('instructor_name', models.CharField(blank=True, max_length=100)),
                ('is_online', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lịch học AI',
                'verbose_name_plural': '4. Lịch học AI',
                'ordering': ['date', 'time_start'],
            },
        ),
    ]
