# Generated by Django 5.2.8 on 2026-01-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_aihealthcareconfig_aihealthcareinstructor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('content', models.TextField(verbose_name='Nội dung liên hệ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Đã xử lý')),
            ],
            options={
                'verbose_name': 'Liên hệ khách hàng',
                'verbose_name_plural': 'Danh sách liên hệ',
                'ordering': ['-created_at'],
            },
        ),
    ]
